version: '2'
services:

  letsrest:
    image: letsrest
    env_file: letsrest.prod.env
    depends_on:
      - mongo
    volumes:
      - /var/log/letsrest:/var/log/letsrest

  mongo:
    image: mongo:3.5.9
    volumes:
      - ./db:/data/db

  nginx:
    image: nginx:1.13.1-alpine
    ports:
      - "80:80"
    depends_on:
      - letsrest
    volumes:
      - /var/log:/var/log
      - ./frontend:/etc/nginx/html/
      - ./nginx.conf:/etc/nginx/nginx.conf
