version: '2'
services:

  letsrest:
    image: letsrest
    env_file: letsrest.prod.env
    volumes:
      - /var/log/letsrest:/var/log/letsrest

  mongo:
    image: mongo:3.9.5
    volumes:
      - ./db:/data/db
